name: test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_auth: ^4.16.0
  fluttertoast: ^8.2.8
  firebase_core: ^2.24.2
  hugeicons: ^0.0.7
  animate_do: ^3.3.4
  shared_preferences: ^2.3.2
  cloud_firestore: ^4.17.5
  firebase_database: ^10.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 # Moved here

flutter_icons: # This section should be under dev_dependencies
  android: true
  ios: true
  image_path: "assets/image/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/background.png
    - assets/image/vatey.JPG
